# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from spooled.grpc.stubs import spooled_pb2 as spooled__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in spooled_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QueueServiceStub(object):
    """Spooled Queue Service
    High-performance gRPC API for job queue operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Enqueue = channel.unary_unary(
                '/spooled.v1.QueueService/Enqueue',
                request_serializer=spooled__pb2.EnqueueRequest.SerializeToString,
                response_deserializer=spooled__pb2.EnqueueResponse.FromString,
                _registered_method=True)
        self.Dequeue = channel.unary_unary(
                '/spooled.v1.QueueService/Dequeue',
                request_serializer=spooled__pb2.DequeueRequest.SerializeToString,
                response_deserializer=spooled__pb2.DequeueResponse.FromString,
                _registered_method=True)
        self.Complete = channel.unary_unary(
                '/spooled.v1.QueueService/Complete',
                request_serializer=spooled__pb2.CompleteRequest.SerializeToString,
                response_deserializer=spooled__pb2.CompleteResponse.FromString,
                _registered_method=True)
        self.Fail = channel.unary_unary(
                '/spooled.v1.QueueService/Fail',
                request_serializer=spooled__pb2.FailRequest.SerializeToString,
                response_deserializer=spooled__pb2.FailResponse.FromString,
                _registered_method=True)
        self.RenewLease = channel.unary_unary(
                '/spooled.v1.QueueService/RenewLease',
                request_serializer=spooled__pb2.RenewLeaseRequest.SerializeToString,
                response_deserializer=spooled__pb2.RenewLeaseResponse.FromString,
                _registered_method=True)
        self.GetJob = channel.unary_unary(
                '/spooled.v1.QueueService/GetJob',
                request_serializer=spooled__pb2.GetJobRequest.SerializeToString,
                response_deserializer=spooled__pb2.GetJobResponse.FromString,
                _registered_method=True)
        self.GetQueueStats = channel.unary_unary(
                '/spooled.v1.QueueService/GetQueueStats',
                request_serializer=spooled__pb2.GetQueueStatsRequest.SerializeToString,
                response_deserializer=spooled__pb2.GetQueueStatsResponse.FromString,
                _registered_method=True)
        self.StreamJobs = channel.unary_stream(
                '/spooled.v1.QueueService/StreamJobs',
                request_serializer=spooled__pb2.StreamJobsRequest.SerializeToString,
                response_deserializer=spooled__pb2.Job.FromString,
                _registered_method=True)
        self.ProcessJobs = channel.stream_stream(
                '/spooled.v1.QueueService/ProcessJobs',
                request_serializer=spooled__pb2.ProcessRequest.SerializeToString,
                response_deserializer=spooled__pb2.ProcessResponse.FromString,
                _registered_method=True)


class QueueServiceServicer(object):
    """Spooled Queue Service
    High-performance gRPC API for job queue operations
    """

    def Enqueue(self, request, context):
        """Enqueue a new job
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dequeue(self, request, context):
        """Dequeue a job (for workers)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Complete(self, request, context):
        """Complete a job
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fail(self, request, context):
        """Fail a job
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewLease(self, request, context):
        """Renew job lease
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """Get job status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQueueStats(self, request, context):
        """Get queue statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamJobs(self, request, context):
        """Stream jobs to workers (server-side streaming)
        Note: Streaming is implemented via REST API WebSocket/SSE endpoints:
        - GET /api/v1/ws (WebSocket for bidirectional real-time updates)
        - GET /api/v1/events (SSE for job event streaming)
        - GET /api/v1/events/jobs/{id} (SSE for single job updates)
        - GET /api/v1/events/queues/{name} (SSE for queue updates)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessJobs(self, request_iterator, context):
        """Bidirectional streaming for real-time job processing
        Note: Use WebSocket endpoint /api/v1/ws for bidirectional communication
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Enqueue': grpc.unary_unary_rpc_method_handler(
                    servicer.Enqueue,
                    request_deserializer=spooled__pb2.EnqueueRequest.FromString,
                    response_serializer=spooled__pb2.EnqueueResponse.SerializeToString,
            ),
            'Dequeue': grpc.unary_unary_rpc_method_handler(
                    servicer.Dequeue,
                    request_deserializer=spooled__pb2.DequeueRequest.FromString,
                    response_serializer=spooled__pb2.DequeueResponse.SerializeToString,
            ),
            'Complete': grpc.unary_unary_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=spooled__pb2.CompleteRequest.FromString,
                    response_serializer=spooled__pb2.CompleteResponse.SerializeToString,
            ),
            'Fail': grpc.unary_unary_rpc_method_handler(
                    servicer.Fail,
                    request_deserializer=spooled__pb2.FailRequest.FromString,
                    response_serializer=spooled__pb2.FailResponse.SerializeToString,
            ),
            'RenewLease': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewLease,
                    request_deserializer=spooled__pb2.RenewLeaseRequest.FromString,
                    response_serializer=spooled__pb2.RenewLeaseResponse.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=spooled__pb2.GetJobRequest.FromString,
                    response_serializer=spooled__pb2.GetJobResponse.SerializeToString,
            ),
            'GetQueueStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQueueStats,
                    request_deserializer=spooled__pb2.GetQueueStatsRequest.FromString,
                    response_serializer=spooled__pb2.GetQueueStatsResponse.SerializeToString,
            ),
            'StreamJobs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamJobs,
                    request_deserializer=spooled__pb2.StreamJobsRequest.FromString,
                    response_serializer=spooled__pb2.Job.SerializeToString,
            ),
            'ProcessJobs': grpc.stream_stream_rpc_method_handler(
                    servicer.ProcessJobs,
                    request_deserializer=spooled__pb2.ProcessRequest.FromString,
                    response_serializer=spooled__pb2.ProcessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spooled.v1.QueueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('spooled.v1.QueueService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QueueService(object):
    """Spooled Queue Service
    High-performance gRPC API for job queue operations
    """

    @staticmethod
    def Enqueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spooled.v1.QueueService/Enqueue',
            spooled__pb2.EnqueueRequest.SerializeToString,
            spooled__pb2.EnqueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Dequeue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spooled.v1.QueueService/Dequeue',
            spooled__pb2.DequeueRequest.SerializeToString,
            spooled__pb2.DequeueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spooled.v1.QueueService/Complete',
            spooled__pb2.CompleteRequest.SerializeToString,
            spooled__pb2.CompleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Fail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spooled.v1.QueueService/Fail',
            spooled__pb2.FailRequest.SerializeToString,
            spooled__pb2.FailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenewLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spooled.v1.QueueService/RenewLease',
            spooled__pb2.RenewLeaseRequest.SerializeToString,
            spooled__pb2.RenewLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spooled.v1.QueueService/GetJob',
            spooled__pb2.GetJobRequest.SerializeToString,
            spooled__pb2.GetJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQueueStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spooled.v1.QueueService/GetQueueStats',
            spooled__pb2.GetQueueStatsRequest.SerializeToString,
            spooled__pb2.GetQueueStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/spooled.v1.QueueService/StreamJobs',
            spooled__pb2.StreamJobsRequest.SerializeToString,
            spooled__pb2.Job.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessJobs(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/spooled.v1.QueueService/ProcessJobs',
            spooled__pb2.ProcessRequest.SerializeToString,
            spooled__pb2.ProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerServiceStub(object):
    """Worker Service for worker management
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/spooled.v1.WorkerService/Register',
                request_serializer=spooled__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=spooled__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/spooled.v1.WorkerService/Heartbeat',
                request_serializer=spooled__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=spooled__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.Deregister = channel.unary_unary(
                '/spooled.v1.WorkerService/Deregister',
                request_serializer=spooled__pb2.DeregisterRequest.SerializeToString,
                response_deserializer=spooled__pb2.DeregisterResponse.FromString,
                _registered_method=True)


class WorkerServiceServicer(object):
    """Worker Service for worker management
    """

    def Register(self, request, context):
        """Register a new worker
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Send heartbeat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deregister(self, request, context):
        """Deregister worker
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=spooled__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=spooled__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=spooled__pb2.HeartbeatRequest.FromString,
                    response_serializer=spooled__pb2.HeartbeatResponse.SerializeToString,
            ),
            'Deregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Deregister,
                    request_deserializer=spooled__pb2.DeregisterRequest.FromString,
                    response_serializer=spooled__pb2.DeregisterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spooled.v1.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('spooled.v1.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """Worker Service for worker management
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spooled.v1.WorkerService/Register',
            spooled__pb2.RegisterWorkerRequest.SerializeToString,
            spooled__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spooled.v1.WorkerService/Heartbeat',
            spooled__pb2.HeartbeatRequest.SerializeToString,
            spooled__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spooled.v1.WorkerService/Deregister',
            spooled__pb2.DeregisterRequest.SerializeToString,
            spooled__pb2.DeregisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
